# Generated by Django 5.2.9 on 2026-01-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0773_add_color_to_user_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="enable_puppet_mode",
            field=models.BooleanField(default=False),
        ),
    ]
