# Generated by Django 5.2.9 on 2026-01-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0774_add_stream_puppet_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="puppet_avatar_url",
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="puppet_display_name",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="puppet_avatar_url",
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="puppet_display_name",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
