# Generated by Django 5.2.9 on 2026-01-08 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0775_add_message_puppet_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamPuppet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("last_used", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puppets",
                        to="zerver.stream",
                    ),
                ),
            ],
            options={
                "unique_together": {("stream", "name")},
            },
        ),
    ]
