# Generated by Django 5.2.9 on 2026-01-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0777_bot_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="streampuppet",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
