# Generated by Django 5.2.9 on 2026-01-31 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0782_realm_max_personas_per_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("claim_token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("verification_code", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, max_length=500, null=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_claim",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["claim_token"], name="zerver_agen_claim_t_cc0026_idx"),
                    models.Index(fields=["claimed"], name="zerver_agen_claimed_643d0b_idx"),
                ],
            },
        ),
    ]
